#!/usr/bin/env bash
set -euo pipefail

VERSION="1.51.0"

# shellcheck source=lib/stdlib
source "$(dirname "${BASH_SOURCE[0]}")/lib/stdlib"

"$TOOL_BUILDER_DIR/lib/build-with-rust" \
    --repo    "https://github.com/casey/just.git" \
    --version "$VERSION" \
    --out     "$(bin_dir)/just"
