---
- name: Install latest LLVM
  hosts: all
  become: true
  vars:
    rel: "{{ ansible_facts['lsb']['codename'] }}"
    llvm_version: 17  # Latest stable LLVM version
  tasks:
    - name: LLVM | add apt key
      ansible.builtin.get_url:
        url: https://apt.llvm.org/llvm-snapshot.gpg.key
        dest: /etc/apt/keyrings/llvm.asc
        mode: ugo+r

    - name: LLVM | add apt repository
      ansible.builtin.apt_repository:
        filename: llvm
        # yamllint disable-line rule:line-length
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/llvm.asc] http://apt.llvm.org/{{ rel }}/ llvm-toolchain-{{ rel }} main

    - name: LLVM | apt install clang & tools
      ansible.builtin.apt:
        pkg:
          - clang
          - clang-tidy
          - clang-format
