---
- name: Install Glab
  hosts: localhost
  tasks:
    - name: Glab | install
      import_tasks: tasks/install-gitlab-release-package.yml
      vars:
        repo_name: gitlab.org/cli
        project_id: 34675721
        release_matcher: '_Linux_x86_64.deb'
