---
- name: Install TaskWarior
  hosts: localhost
  tasks:
    - name: Taskwarrior | apt install
      become: true
      ansible.builtin.apt:
        pkg:
          - taskwarrior
          - timewarrior

    - name: Task warrior | install timew hook
      ansible.builtin.file:
        src: /usr/share/doc/timewarrior/ext/on-modify.timewarrior
        dest: /home/tch/.task/hooks/on-modify.timewarrior
        state: link
        mode: "0775"
