---
- name: Install Python3 & Core Tools
  hosts: localhost
  become: true
  tasks:
    - name: Python | install core tools
      ansible.builtin.apt:
        pkg:
          - pipx
          - python-is-python3
          - python3-pip
          - python3-venv

    - name: Python | install core libraries
      ansible.builtin.apt:
        pkg:
          - python3-click
          - python3-rich

    - name: Python | install common tools
      loop:
        - black
        - poetry
        - pre-commit
        - yamllint
      become: false
      community.general.pipx:
        # By default, the command runs `python -m pipx`. This doesn't work if
        # ansible was installed with pipx since the python interpreter running
        # ansible does not pipx installed.
        # Instead we use the system pipx
        executable: pipx
        name: "{{ item }}"
