---
- name: "{{ github_repo | title }} | fetch latest release"
  uri:
    # yamllint disable-line rule:line-length
    url: https://api.github.com/repos/{{ github_user }}/{{ github_repo }}/releases/latest
  register: latest_release

- name: "{{ github_repo | title }} | install package"
  loop: "{{ latest_release.json.assets }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name is regex('x86_64-unknown-linux-gnu\.tar\.gz$')
  ansible.builtin.unarchive:
    src: "{{ item.browser_download_url }}"
    remote_src: true
    dest: ~/.local/bin/
