---
- name: "{{ github_repo | title }} | fetch latest release"
  uri:
    # yamllint disable-line rule:line-length
    url: https://api.github.com/repos/{{ github_user }}/{{ github_repo }}/releases/latest
  register: latest_release

- name: "{{ github_repo | title }} | install package"
  loop: "{{ latest_release.json.assets }}"
  loop_control:
    label: "{{ item.name }}"
  when: "'_amd64.deb' in item.name"
  become: true
  ansible.builtin.apt:
    deb: "{{ item.browser_download_url }}"
